import React from 'react'

export default function LandingPage() {
    return (
        <div className='landing-page'>
            <img className='auth-background-img' src='http://localhost:5000/lion.png' alt='background image'/>
            <section>
                <h1>
                    Welcome to Awake Studios
                </h1>
                <article>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut veritatis commodi eius dolores cumque eligendi? Similique reiciendis provident nemo laborum iusto blanditiis nulla, dolor quis voluptatum sit accusamus ipsa unde eos laudantium accusantium sunt perferendis ipsam corporis magnam earum voluptatibus quisquam odit. Illo quod quia hic velit adipisci aliquid enim deserunt, delectus distinctio. Repellendus asperiores aliquid voluptatibus. Laborum libero sint minima itaque nam saepe voluptatem nostrum facere sed reprehenderit, quaerat voluptatum sequi provident consequuntur cum qui dicta voluptates accusamus ea nobis, ut quo odit dolores exercitationem. Ullam, excepturi, laboriosam eaque officia nesciunt iusto nobis nulla dolorum neque harum, soluta labore.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut veritatis commodi eius dolores cumque eligendi? Similique reiciendis provident nemo laborum iusto blanditiis nulla, dolor quis voluptatum sit accusamus ipsa unde eos laudantium accusantium sunt perferendis ipsam corporis magnam earum voluptatibus quisquam odit. Illo quod quia hic velit adipisci aliquid enim deserunt, delectus distinctio. Repellendus asperiores aliquid voluptatibus. Laborum libero sint minima itaque nam saepe voluptatem nostrum facere sed reprehenderit, quaerat voluptatum sequi provident consequuntur cum qui dicta voluptates accusamus ea nobis, ut quo odit dolores exercitationem. Ullam, excepturi, laboriosam eaque officia nesciunt iusto nobis nulla dolorum neque harum, soluta labore.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut veritatis commodi eius dolores cumque eligendi? Similique reiciendis provident nemo laborum iusto blanditiis nulla, dolor quis voluptatum sit accusamus ipsa unde eos laudantium accusantium sunt perferendis ipsam corporis magnam earum voluptatibus quisquam odit. Illo quod quia hic velit adipisci aliquid enim deserunt, delectus distinctio. Repellendus asperiores aliquid voluptatibus. Laborum libero sint minima itaque nam saepe voluptatem nostrum facere sed reprehenderit, quaerat voluptatum sequi provident consequuntur cum qui dicta voluptates accusamus ea nobis, ut quo odit dolores exercitationem. Ullam, excepturi, laboriosam eaque officia nesciunt iusto nobis nulla dolorum neque harum, soluta labore.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut veritatis commodi eius dolores cumque eligendi? Similique reiciendis provident nemo laborum iusto blanditiis nulla, dolor quis voluptatum sit accusamus ipsa unde eos laudantium accusantium sunt perferendis ipsam corporis magnam earum voluptatibus quisquam odit. Illo quod quia hic velit adipisci aliquid enim deserunt, delectus distinctio. Repellendus asperiores aliquid voluptatibus. Laborum libero sint minima itaque nam saepe voluptatem nostrum facere sed reprehenderit, quaerat voluptatum sequi provident consequuntur cum qui dicta voluptates accusamus ea nobis, ut quo odit dolores exercitationem. Ullam, excepturi, laboriosam eaque officia nesciunt iusto nobis nulla dolorum neque harum, soluta labore.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut veritatis commodi eius dolores cumque eligendi? Similique reiciendis provident nemo laborum iusto blanditiis nulla, dolor quis voluptatum sit accusamus ipsa unde eos laudantium accusantium sunt perferendis ipsam corporis magnam earum voluptatibus quisquam odit. Illo quod quia hic velit adipisci aliquid enim deserunt, delectus distinctio. Repellendus asperiores aliquid voluptatibus. Laborum libero sint minima itaque nam saepe voluptatem nostrum facere sed reprehenderit, quaerat voluptatum sequi provident consequuntur cum qui dicta voluptates accusamus ea nobis, ut quo odit dolores exercitationem. Ullam, excepturi, laboriosam eaque officia nesciunt iusto nobis nulla dolorum neque harum, soluta labore.</p>
                </article>
            </section>
        </div>
    )
}
